name: run_exercies

on:
  workflow_dispatch:


jobs:
  exercises:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls
    - name: pwd
      run: pwd
    - name: run_chapter1_exercises
      run: cd chapter1 && ./run_all.sh
    - name: pwd2
      run: pwd

